name: "Validate Gradle Wrapper"

on:
  push: { }
  pull_request: { }

jobs:
  validation:
    name: "Gradle Wrapper validation"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: gradle/wrapper-validation-action@v1
